Instalación de la libreia deap, si requiere mayor información consultar:

https://deap.readthedocs.io/en/master/

Integrantes:
Adrian Felipe Gironza - Arlex Fabian Galindez


In [26]:
!pip install deap

from deap import algorithms
from deap import base
from deap import creator
from deap import tools
import random
import numpy as np
import json
from collections import Counter
import copy


np.set_printoptions(suppress=True)

def cargar_datos_asignaturas():
    # Cargar los datos de asignaturas desde un archivo JSON
    with open("asignaturas.json", encoding="utf-8-sig") as file:
        datos = json.load(file)
    return datos

def cargar_datos_salones():
    # Cargar los datos de salones desde un archivo JSON
    with open("salones.json", encoding="utf-8-sig") as file:
        datos_sal = json.load(file)
    return datos_sal

datos_asignaturas = cargar_datos_asignaturas()
datos_salones = cargar_datos_salones()

cantasignaturas = len(datos_asignaturas)
cantdias = 5
cantfranjas=5
cantsalones= len(datos_salones)
valorlibre = 777

def initIndividual(icls):

    ind = iniciarmatriz(cantdias,cantfranjas,cantsalones)
    ind = asignarmaterias(ind)
    ind = corregir_asignaturas_repetidas(ind)
    ind = corregir_profesores_repetidos(ind)
    ind = corregir_semestres_repetidos(ind)
    ind = corregir_asignaturas_por_dia(ind)
    print("Individuo generado: \n",ind, "\nfin")
    return icls(ind)

def iniciarmatriz(x, y, z):
    matriz = np.zeros((x, y, z),dtype=np.int)
    valor_predeterminado = valorlibre
    for i in range(x):
        for j in range(y):
            for k in range(z):
                matriz[i, j, k] = valor_predeterminado
    return matriz

def asignarmaterias(ind):
    lind = ind.ravel()
    for asignatura in range(cantasignaturas):
        jornasignadas = datos_asignaturas[asignatura]["JORNEC"]
        for j in range(jornasignadas):  # Utilizamos _ para indicar que no se usa la variable de iteración
            while True:
                posicion_aleatoria = random.randint(0, len(lind) - 1)
                if lind[posicion_aleatoria] == valorlibre:
                    lind[posicion_aleatoria] = asignatura
                    break
    #print("Individuo 1D\n", lind)
    nind = lind.reshape(cantdias, cantfranjas, cantsalones)
    return nind


def corregir_asignaturas_repetidas(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            salones = individuo[dia, franja]  # Obtener los salones asignados en la franja horaria
            asignaturas = list(set(salones))  # Obtener las asignaturas únicas en la franja
            if len(asignaturas) < len(salones):
                for asignatura in asignaturas:
                    indices = np.where(salones == asignatura)[0]  # Obtener los índices de la asignatura
                    if len(indices) > 1:
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if salones[posicion] != valorlibre:
                                # Cambiar la asignatura de franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = salones[posicion]
                                salones[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_profesores_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):  # Iterar sobre los salones en la franja horaria
                asignatura = (individuo[dia, franja, salon])
                if asignatura != valorlibre:
                    profesor = datos_asignaturas[asignatura]['PROFESOR']
                    # Verificar si hay más de una asignatura asignada al mismo profesor en la franja horaria
                    otras_asignaturas = [individuo[dia, franja, s] for s in range(cantsalones) if s != salon]
                    if otras_asignaturas.count(asignatura) > 0:
                        nueva_franja = (franja + 1) % cantfranjas  # Obtener la siguiente franja horaria
                        nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                        individuo[dia, nueva_franja, nueva_salon] = asignatura
                        individuo[dia, franja, salon] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_semestres_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            asignaturas = individuo[dia, franja]  # Obtener las asignaturas de la franja
            semestres = set()
            for asignatura in asignaturas:
                if asignatura != valorlibre:  # Ignorar las asignaturas no asignadas
                    semestre = datos_asignaturas[asignatura]['ASIGNATURA']
                    if semestre in semestres:
                        # Encontró asignatura repetida del mismo semestre
                        indices = np.where(asignaturas == asignatura)[0]
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if asignaturas[posicion] != valorlibre:
                                # Buscar otro salón aleatorio libre en otra franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = asignaturas[posicion]
                                asignaturas[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
                    semestres.add(semestre)
    return individuo

def corregir_asignaturas_por_dia(individuo):
    for dia in range(cantdias):
        asignaturas_dia = individuo[dia]  # Obtener las asignaturas del día
        asignaturas_unicas = np.unique(asignaturas_dia)  # Obtener las asignaturas únicas
        if len(asignaturas_unicas) < len(asignaturas_dia):
            asignaturas_asignadas = set()
            for i in range(cantfranjas):
                for j in range(cantsalones):
                    asignatura = asignaturas_dia[i, j]
                    if asignatura != valorlibre:
                        if asignatura in asignaturas_asignadas:
                            # Buscar otra franja y salón aleatorio que esté libre y no tenga asignatura duplicada
                            nueva_franja = random.randint(0, cantfranjas - 1)
                            nueva_salon = random.randint(0, cantsalones - 1)
                            while individuo[dia, nueva_franja, nueva_salon] != valorlibre or individuo[dia, nueva_franja, nueva_salon] in asignaturas_asignadas:
                                nueva_franja = random.randint(0, cantfranjas - 1)
                                nueva_salon = random.randint(0, cantsalones - 1)
                            # Realizar el intercambio de asignaturas
                            individuo[dia, i, j] = individuo[dia, nueva_franja, nueva_salon]
                            individuo[dia, nueva_franja, nueva_salon] = asignatura
                        else:
                            asignaturas_asignadas.add(asignatura)
    return individuo



creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", np.ndarray, fitness=creator.FitnessMin)
toolbox = base.Toolbox()
toolbox.register("individual_guess", initIndividual, creator.Individual)
toolbox.register("population", tools.initRepeat, list, toolbox.individual_guess)

def evalOneMax(individual):
    fitness = 0
    return (fitness,)

def validar_profesor_nn(individuo):
    contador = 0
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            asignaturas = individuo[dia, franja, :] # Obtener las asignaturas de la franja
            profesores = [datos_asignaturas[asignatura]["PROFESOR"] for asignatura in asignaturas]
            contador_nn = sum(1 for p in profesores if p in ["NN3", "Becario", "Asistente de Docencia"])
            if contador_nn > 1:
                contador += 1
    return contador

def validar_franjas_asignatura(individuo):
    contador_repetidas = 0
    for dia in range(cantdias):
        for asignatura in range(cantasignaturas):
            franjas_dia = individuo[dia, :, :].flatten()  # Obtener todas las franjas del día
            frecuencias = Counter(franjas_dia)
            asignatura_repetida = [frecuencia for _, frecuencia in frecuencias.items() if frecuencia > 1]
            if asignatura_repetida:
                contador_repetidas += 1
    return contador_repetidas

def validar_tipo_asignatura(individuo):
    contador = 0
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                codigo_asignatura = individuo[dia, franja, salon]
                asignatura = datos_asignaturas[codigo_asignatura]
                tipo_asignatura = asignatura['TIPOAS']
                tipo_salon = datos_salones[salon]['TIPO']
                if tipo_asignatura == 'T' and tipo_salon != 'TEORICO':
                    contador += 1
                if tipo_asignatura == 'P' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'TP' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'P' and int(asignatura['ASIGNATURA']) >= 7 and datos_salones[salon]['CODIGO'] != 'Sala 4':
                    contador += 1
    return contador

def cxTwoPointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoints = sorted(random.sample(range(1, size), 2))
    for i in range(len(cxpoints)):
        cxpoint1, cxpoint2 = cxpoints[i-1], cxpoints[i]
        temp_ind1 = ind1[cxpoint1:cxpoint2].copy()
        temp_ind2 = ind2[cxpoint1:cxpoint2].copy()

        for dia in range(cantdias):
            for franja in range(cantfranjas):
                for salon in range(cantsalones):
                    if ind1[dia, franja, salon] in temp_ind2:
                        ind1[dia, franja, salon] = temp_ind2[temp_ind2 == ind1[dia, franja, salon]][0]
                    if ind2[dia, franja, salon] in temp_ind1:
                        ind2[dia, franja, salon] = temp_ind1[temp_ind1 == ind2[dia, franja, salon]][0]

    return ind1, ind2

def cxOnePointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoint = random.randint(1, size-1)
    ind1[cxpoint:], ind2[cxpoint:] = copy.deepcopy(ind2[cxpoint:]), copy.deepcopy(ind1[cxpoint:])
    return ind1, ind2

def mutFlipBit(individual, indpb):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                if random.random() < indpb:
                    individual[dia, franja, salon] = random.randint(0, cantasignaturas-1)
    return individual,


toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", cxTwoPointCopy)
toolbox.register("mutate", mutFlipBit, indpb=0.1)
toolbox.register("select", tools.selTournament, tournsize=3)



def initIndividual(icls):

    ind = iniciarmatriz(cantdias,cantfranjas,cantsalones)
    ind = asignarmaterias(ind)
    ind = corregir_asignaturas_repetidas(ind)
    ind = corregir_profesores_repetidos(ind)
    ind = corregir_semestres_repetidos(ind)
    ind = corregir_asignaturas_por_dia(ind)
    print("Individuo generado: \n",ind, "\nfin")
    return icls(ind)

def iniciarmatriz(x, y, z):
    matriz = np.zeros((x, y, z),dtype=np.int)
    valor_predeterminado = valorlibre
    for i in range(x):
        for j in range(y):
            for k in range(z):
                matriz[i, j, k] = valor_predeterminado
    return matriz

def asignarmaterias(ind):
    lind = ind.ravel()
    for asignatura in range(cantasignaturas):
        jornasignadas = datos_asignaturas[asignatura]["JORNEC"]
        for j in range(jornasignadas):  # Utilizamos _ para indicar que no se usa la variable de iteración
            while True:
                posicion_aleatoria = random.randint(0, len(lind) - 1)
                if lind[posicion_aleatoria] == valorlibre:
                    lind[posicion_aleatoria] = asignatura
                    break
    #print("Individuo 1D\n", lind)
    nind = lind.reshape(cantdias, cantfranjas, cantsalones)
    return nind


def corregir_asignaturas_repetidas(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            salones = individuo[dia, franja]  # Obtener los salones asignados en la franja horaria
            asignaturas = list(set(salones))  # Obtener las asignaturas únicas en la franja
            if len(asignaturas) < len(salones):
                for asignatura in asignaturas:
                    indices = np.where(salones == asignatura)[0]  # Obtener los índices de la asignatura
                    if len(indices) > 1:
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if salones[posicion] != valorlibre:
                                # Cambiar la asignatura de franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = salones[posicion]
                                salones[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_profesores_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):  # Iterar sobre los salones en la franja horaria
                asignatura = (individuo[dia, franja, salon])
                if asignatura != valorlibre:
                    profesor = datos_asignaturas[asignatura]['PROFESOR']
                    # Verificar si hay más de una asignatura asignada al mismo profesor en la franja horaria
                    otras_asignaturas = [individuo[dia, franja, s] for s in range(cantsalones) if s != salon]
                    if otras_asignaturas.count(asignatura) > 0:
                        nueva_franja = (franja + 1) % cantfranjas  # Obtener la siguiente franja horaria
                        nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                        individuo[dia, nueva_franja, nueva_salon] = asignatura
                        individuo[dia, franja, salon] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_semestres_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            asignaturas = individuo[dia, franja]  # Obtener las asignaturas de la franja
            semestres = set()
            for asignatura in asignaturas:
                if asignatura != valorlibre:  # Ignorar las asignaturas no asignadas
                    semestre = datos_asignaturas[asignatura]['ASIGNATURA']
                    if semestre in semestres:
                        # Encontró asignatura repetida del mismo semestre
                        indices = np.where(asignaturas == asignatura)[0]
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if asignaturas[posicion] != valorlibre:
                                # Buscar otro salón aleatorio libre en otra franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = asignaturas[posicion]
                                asignaturas[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
                    semestres.add(semestre)
    return individuo

def corregir_asignaturas_por_dia(individuo):
    for dia in range(cantdias):
        asignaturas_dia = individuo[dia]  # Obtener las asignaturas del día
        asignaturas_unicas = np.unique(asignaturas_dia)  # Obtener las asignaturas únicas
        if len(asignaturas_unicas) < len(asignaturas_dia):
            asignaturas_asignadas = set()
            for i in range(cantfranjas):
                for j in range(cantsalones):
                    asignatura = asignaturas_dia[i, j]
                    if asignatura != valorlibre:
                        if asignatura in asignaturas_asignadas:
                            # Buscar otra franja y salón aleatorio que esté libre y no tenga asignatura duplicada
                            nueva_franja = random.randint(0, cantfranjas - 1)
                            nueva_salon = random.randint(0, cantsalones - 1)
                            while individuo[dia, nueva_franja, nueva_salon] != valorlibre or individuo[dia, nueva_franja, nueva_salon] in asignaturas_asignadas:
                                nueva_franja = random.randint(0, cantfranjas - 1)
                                nueva_salon = random.randint(0, cantsalones - 1)
                            # Realizar el intercambio de asignaturas
                            individuo[dia, i, j] = individuo[dia, nueva_franja, nueva_salon]
                            individuo[dia, nueva_franja, nueva_salon] = asignatura
                        else:
                            asignaturas_asignadas.add(asignatura)
    return individuo



creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", np.ndarray, fitness=creator.FitnessMin)
toolbox = base.Toolbox()
toolbox.register("individual_guess", initIndividual, creator.Individual)
toolbox.register("population", tools.initRepeat, list, toolbox.individual_guess)

def evalOneMax(individual):
    fitness = 0
    return (fitness,)

def validar_profesor_nn(individuo):
    contador = 0
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            asignaturas = individuo[dia, franja, :] # Obtener las asignaturas de la franja
            profesores = [datos_asignaturas[asignatura]["PROFESOR"] for asignatura in asignaturas]
            contador_nn = sum(1 for p in profesores if p in ["NN3", "Becario", "Asistente de Docencia"])
            if contador_nn > 1:
                contador += 1
    return contador

def validar_franjas_asignatura(individuo):
    contador_repetidas = 0
    for dia in range(cantdias):
        for asignatura in range(cantasignaturas):
            franjas_dia = individuo[dia, :, :].flatten()  # Obtener todas las franjas del día
            frecuencias = Counter(franjas_dia)
            asignatura_repetida = [frecuencia for _, frecuencia in frecuencias.items() if frecuencia > 1]
            if asignatura_repetida:
                contador_repetidas += 1
    return contador_repetidas

def validar_tipo_asignatura(individuo):
    contador = 0
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                codigo_asignatura = individuo[dia, franja, salon]
                asignatura = datos_asignaturas[codigo_asignatura]
                tipo_asignatura = asignatura['TIPOAS']
                tipo_salon = datos_salones[salon]['TIPO']
                if tipo_asignatura == 'T' and tipo_salon != 'TEORICO':
                    contador += 1
                if tipo_asignatura == 'P' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'TP' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'P' and int(asignatura['ASIGNATURA']) >= 7 and datos_salones[salon]['CODIGO'] != 'Sala 4':
                    contador += 1
    return contador

def cxTwoPointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoints = sorted(random.sample(range(1, size), 2))
    for i in range(len(cxpoints)):
        cxpoint1, cxpoint2 = cxpoints[i-1], cxpoints[i]
        temp_ind1 = ind1[cxpoint1:cxpoint2].copy()
        temp_ind2 = ind2[cxpoint1:cxpoint2].copy()

        for dia in range(cantdias):
            for franja in range(cantfranjas):
                for salon in range(cantsalones):
                    if ind1[dia, franja, salon] in temp_ind2:
                        ind1[dia, franja, salon] = temp_ind2[temp_ind2 == ind1[dia, franja, salon]][0]
                    if ind2[dia, franja, salon] in temp_ind1:
                        ind2[dia, franja, salon] = temp_ind1[temp_ind1 == ind2[dia, franja, salon]][0]

    return ind1, ind2

def cxOnePointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoint = random.randint(1, size-1)
    ind1[cxpoint:], ind2[cxpoint:] = copy.deepcopy(ind2[cxpoint:]), copy.deepcopy(ind1[cxpoint:])
    return ind1, ind2

def mutFlipBit(individual, indpb):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                if random.random() < indpb:
                    individual[dia, franja, salon] = random.randint(0, cantasignaturas-1)
    return individual,


toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", cxTwoPointCopy)
toolbox.register("mutate", mutFlipBit, indpb=0.1)
toolbox.register("select", tools.selTournament, tournsize=3)



def initIndividual(icls):

    ind = iniciarmatriz(cantdias,cantfranjas,cantsalones)
    ind = asignarmaterias(ind)
    ind = corregir_asignaturas_repetidas(ind)
    ind = corregir_profesores_repetidos(ind)
    ind = corregir_semestres_repetidos(ind)
    ind = corregir_asignaturas_por_dia(ind)
    print("Individuo generado: \n",ind, "\nfin")
    return icls(ind)

def iniciarmatriz(x, y, z):
    matriz = np.zeros((x, y, z),dtype=np.int)
    valor_predeterminado = valorlibre
    for i in range(x):
        for j in range(y):
            for k in range(z):
                matriz[i, j, k] = valor_predeterminado
    return matriz

def asignarmaterias(ind):
    lind = ind.ravel()
    for asignatura in range(cantasignaturas):
        jornasignadas = datos_asignaturas[asignatura]["JORNEC"]
        for j in range(jornasignadas):  # Utilizamos _ para indicar que no se usa la variable de iteración
            while True:
                posicion_aleatoria = random.randint(0, len(lind) - 1)
                if lind[posicion_aleatoria] == valorlibre:
                    lind[posicion_aleatoria] = asignatura
                    break
    #print("Individuo 1D\n", lind)
    nind = lind.reshape(cantdias, cantfranjas, cantsalones)
    return nind


def corregir_asignaturas_repetidas(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            salones = individuo[dia, franja]  # Obtener los salones asignados en la franja horaria
            asignaturas = list(set(salones))  # Obtener las asignaturas únicas en la franja
            if len(asignaturas) < len(salones):
                for asignatura in asignaturas:
                    indices = np.where(salones == asignatura)[0]  # Obtener los índices de la asignatura
                    if len(indices) > 1:
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if salones[posicion] != valorlibre:
                                # Cambiar la asignatura de franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = salones[posicion]
                                salones[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_profesores_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):  # Iterar sobre los salones en la franja horaria
                asignatura = (individuo[dia, franja, salon])
                if asignatura != valorlibre:
                    profesor = datos_asignaturas[asignatura]['PROFESOR']
                    # Verificar si hay más de una asignatura asignada al mismo profesor en la franja horaria
                    otras_asignaturas = [individuo[dia, franja, s] for s in range(cantsalones) if s != salon]
                    if otras_asignaturas.count(asignatura) > 0:
                        nueva_franja = (franja + 1) % cantfranjas  # Obtener la siguiente franja horaria
                        nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                        individuo[dia, nueva_franja, nueva_salon] = asignatura
                        individuo[dia, franja, salon] = valorlibre  # Marcar la asignatura como libre en la franja original
    return individuo

def corregir_semestres_repetidos(individuo):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            asignaturas = individuo[dia, franja]  # Obtener las asignaturas de la franja
            semestres = set()
            for asignatura in asignaturas:
                if asignatura != valorlibre:  # Ignorar las asignaturas no asignadas
                    semestre = datos_asignaturas[asignatura]['ASIGNATURA']
                    if semestre in semestres:
                        # Encontró asignatura repetida del mismo semestre
                        indices = np.where(asignaturas == asignatura)[0]
                        for i in range(1, len(indices)):
                            posicion = indices[i]
                            if asignaturas[posicion] != valorlibre:
                                # Buscar otro salón aleatorio libre en otra franja
                                nueva_franja = (franja + i) % cantfranjas
                                nueva_salon = np.where(individuo[dia, nueva_franja] == valorlibre)[0][0]
                                individuo[dia, nueva_franja, nueva_salon] = asignaturas[posicion]
                                asignaturas[posicion] = valorlibre  # Marcar la asignatura como libre en la franja original
                    semestres.add(semestre)
    return individuo

def corregir_asignaturas_por_dia(individuo):
    for dia in range(cantdias):
        asignaturas_dia = individuo[dia]  # Obtener las asignaturas del día
        asignaturas_unicas = np.unique(asignaturas_dia)  # Obtener las asignaturas únicas
        if len(asignaturas_unicas) < len(asignaturas_dia):
            asignaturas_asignadas = set()
            for i in range(cantfranjas):
                for j in range(cantsalones):
                    asignatura = asignaturas_dia[i, j]
                    if asignatura != valorlibre:
                        if asignatura in asignaturas_asignadas:
                            # Buscar otra franja y salón aleatorio que esté libre y no tenga asignatura duplicada
                            nueva_franja = random.randint(0, cantfranjas - 1)
                            nueva_salon = random.randint(0, cantsalones - 1)
                            while individuo[dia, nueva_franja, nueva_salon] != valorlibre or individuo[dia, nueva_franja, nueva_salon] in asignaturas_asignadas:
                                nueva_franja = random.randint(0, cantfranjas - 1)
                                nueva_salon = random.randint(0, cantsalones - 1)
                            # Realizar el intercambio de asignaturas
                            individuo[dia, i, j] = individuo[dia, nueva_franja, nueva_salon]
                            individuo[dia, nueva_franja, nueva_salon] = asignatura
                        else:
                            asignaturas_asignadas.add(asignatura)
    return individuo



creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", np.ndarray, fitness=creator.FitnessMin)
toolbox = base.Toolbox()
toolbox.register("individual_guess", initIndividual, creator.Individual)
toolbox.register("population", tools.initRepeat, list, toolbox.individual_guess)

def evalOneMax(ind):
    fitness = 0
    fitness += validar_profesor_nn(ind)
    fitness += validar_franjas_asignatura(ind)
    fitness += validar_tipo_asignatura(ind)
    return (fitness,)

def validar_tipo_asignatura(individuo):
    contador = 0
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                codigo_asignatura = individuo[dia, franja, salon]
                asignatura = datos_asignaturas[codigo_asignatura]
                tipo_asignatura = asignatura['TIPOAS']
                tipo_salon = datos_salones[salon]['TIPO']
                if tipo_asignatura == 'T' and tipo_salon != 'TEORICO':
                    contador += 1
                if tipo_asignatura == 'P' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'TP' and tipo_salon != 'LAB':
                    contador += 1
                if tipo_asignatura == 'P' and int(asignatura['ASIGNATURA']) >= 7 and datos_salones[salon]['CODIGO'] != 'Sala 4':
                    contador += 1
    return contador

def cxTwoPointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoints = sorted(random.sample(range(1, size), 2))
    for i in range(len(cxpoints)):
        cxpoint1, cxpoint2 = cxpoints[i-1], cxpoints[i]
        temp_ind1 = ind1[cxpoint1:cxpoint2].copy()
        temp_ind2 = ind2[cxpoint1:cxpoint2].copy()

        for dia in range(cantdias):
            for franja in range(cantfranjas):
                for salon in range(cantsalones):
                    if ind1[dia, franja, salon] in temp_ind2:
                        ind1[dia, franja, salon] = temp_ind2[temp_ind2 == ind1[dia, franja, salon]][0]
                    if ind2[dia, franja, salon] in temp_ind1:
                        ind2[dia, franja, salon] = temp_ind1[temp_ind1 == ind2[dia, franja, salon]][0]

    return ind1, ind2

def cxOnePointCopy(ind1, ind2):
    size = min(len(ind1), len(ind2))
    cxpoint = random.randint(1, size-1)
    ind1[cxpoint:], ind2[cxpoint:] = copy.deepcopy(ind2[cxpoint:]), copy.deepcopy(ind1[cxpoint:])
    return ind1, ind2

def mutFlipBit(individual, indpb):
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                if random.random() < indpb:
                    individual[dia, franja, salon] = random.randint(0, cantasignaturas-1)
    return individual,


toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", cxTwoPointCopy)
toolbox.register("mutate", mutFlipBit, indpb=0.1)
toolbox.register("select", tools.selTournament, tournsize=3)

def main():
    random.seed(64)

    pop = toolbox.population(n=2)
    hof = tools.HallOfFame(1, similar=np.array_equal)

    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)

    algorithms.eaSimple(pop, toolbox, cxpb=0.5,mutpb=0.1, ngen=10, stats=stats,halloffame=hof)

    best_individual = hof[0]
    print('Mejor solución:', best_individual)

    horario = decode_individual(best_individual)
    print('Horario:')
    print_horario(horario)

    return pop, stats, hof

def decode_individual(individual):
    horario = np.zeros((cantdias, cantfranjas, cantsalones), dtype=object)
    for dia in range(cantdias):
        for franja in range(cantfranjas):
            for salon in range(cantsalones):
                codigo_asignatura = individual[dia, franja, salon]
                if codigo_asignatura != valorlibre:
                    asignatura = datos_asignaturas[codigo_asignatura]
                    nombre_asignatura = asignatura['NOMBRE']
                    profesor = asignatura['PROFESOR']

                    codigo_salon = datos_salones[salon]['CODIGO']  # Obtener código del salón

                    franja_horaria = f'{franja}-{franja+1}'
                    horario[dia, franja, salon] = (nombre_asignatura, profesor, franja_horaria, codigo_salon)
    return horario


def print_horario(horario):
    for dia in range(cantdias):
        print(f'Día {dia+1}:')
        for franja in range(cantfranjas):
            print(f'Franja horaria {franja+1}-{franja+2}:')
            for salon in range(cantsalones):
                asignatura = horario[dia, franja, salon]
                if asignatura:
                    nombre_asignatura, profesor, franja_horaria, codigo_salon = asignatura
                    print(f'Salón {codigo_salon}: {nombre_asignatura} - Profesor: {profesor}')
            print()
        print()


if __name__ == "__main__":
    p, s, h = main()


Individuo generado: 
 [[[ 29 777  13 777  73 777 777 777   3 777 777  91  11 777 777  19]
  [777 777 777  57 777 777  43  15 777  28 777  44  31 777 777 777]
  [ 13 777 777 777 777 777 777 777   9 777  12  99 777  18  91 777]
  [777  89 777 777 777  14 777  63  45  34  93 777 777 777  97   0]
  [ 45  44 777 777 777  71  22 777  59 777 777   8  38 777  95  43]]

 [[ 35 777  30 777 777 777  46  42 777  14 777  28 777 777 777  80]
  [777 777 777 777  18  10 777   6   4 100  97 777 777  21 777  32]
  [ 17 777  36  98 777  82  29 777 777  37 777 777  38  33 777 777]
  [ 49 777  85 777  39 777 777  16 777   4 777 777  42 777  83  32]
  [777 777 777 777 777 777  96  21  35  40 777  34 777  25  74 777]]

 [[ 58 777  53 777 777 777  72 777  65 777  47  98 777 777 777 777]
  [777 777 777  96 777 777 777  24  88  85  26 777 777 777  41  70]
  [777  93 777  79  94  99  69 777  68 777 777  20 777 777   2 777]
  [ 92 777 777 777 777   9 777 777  50  39  23 777 777 777 777 777]
  [777  10 777  40 777

/usr/local/lib/python3.10/dist-packages/deap/creator.py:138: RuntimeWarning: A class named 'FitnessMin' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
/usr/local/lib/python3.10/dist-packages/deap/creator.py:138: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
<ipython-input-26-07bc45850874>:467: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecate

IndexError: ignored

EVALUACION

CRUCE

MUTACION